name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest  

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js # setup Node.js in the runner
        uses: actions/setup-node@v1
        with:
          node-version: '12'm
    - run: npm ci
    - run: npm install
    - run: pm2 kill && pm2 start main.js
